apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skygear.secret.name" . | quote }}
  labels:
    {{- include "skygear.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $pgbouncer := include "skygear.pgbouncer.name" . }}
  API_KEY: {{ .Values.apiKey | b64enc | quote }}
  MASTER_KEY: {{ .Values.masterKey | b64enc | quote }}
  SENTRY_DNS: {{ .Values.sentryDNS | b64enc | quote }}
  TOKEN_STORE_SECRET: {{ .Values.tokenStoreSecret | b64enc | quote }}
  CUSTOM_TOKEN_SECRET: {{ .Values.customTokenSecret | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s.%s.svc.cluster.local/poolsession?sslmode=disable" .Values.database.username .Values.database.password $pgbouncer .Release.Namespace | b64enc | quote }}
  DATABASE_HOST: {{ .Values.database.host | b64enc | quote }}
  DATABASE_PORT: {{ .Values.database.port | toString | b64enc | quote }}
  DATABASE_USER: {{ .Values.database.username | b64enc | quote }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DATABASE_NAME: {{ .Values.database.name | b64enc | quote }}
  CLOUD_ASSET_TOKEN: {{ .Values.assetStore.cloud.token | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | b64enc | quote }}
  GCM_APIKEY: {{ .Values.gcm.apiKey | b64enc | quote }}
  {{- if .Values.fcm.serverKey }}
  FCM_SERVER_KEY: {{ .Values.fcm.serverKey | b64enc | quote }}
  {{- end }}
  APNS_TOKEN_KEY: {{ .Values.apns.tokenKey | b64enc | quote }}
  APNS_CERTIFICATE: {{ .Values.apns.certificate | b64enc | quote }}
  APNS_PRIVATE_KEY: {{ .Values.apns.privateKey | b64enc | quote }}
  ASSET_STORE_ACCESS_KEY: {{ .Values.assetStore.s3.accessKey | b64enc | quote }}
  ASSET_STORE_SECRET_KEY: {{ .Values.assetStore.s3.secretKey | b64enc | quote }}
