image: __replace__
appName: __replace__
publicHost: __replace__
urlPrefix: __replace__
apiKey: __replace__
masterKey: __replace__
sentryDNS: __replace__
deisRelease: __replace__
tokenStoreSecret: __replace__
customTokenSecret: __replace__
logLevel: "error"
devMode: "NO"

extraEnv: []
envFromSecretName: ""
resources:
  limits:
    cpu: "1"
    memory: 256Mi
  requests:
    cpu: 50m
    memory: 64Mi

database:
  host: __replace__
  port: 5432
  username: __replace__
  password: __replace__
  name: __replace__

staticAsset:
  host: production.static-assets.skygeario.com
  hash: __replace__

assetStore:
  type: "cloud"
  isPublic: false
  cloud:
    host: https://asset.skygeario.com
    token: __replace__
    publicPrefix: __replace__
    privatePrefix: __replace__
  s3:
    region: __replace__
    bucket: __replace__
    accessKey: __replace__
    secretKey: __replace__
    urlPrefix: ""

smtp:
  password: __replace__

cms:
  configFileURL: ""

gcm:
  enabled: false
  apiKey: __replace__

fcm:
  enabled: false
  serverKey: ""

apns:
  enabled: false
  type: token
  teamID: __replace__
  keyID: __replace__
  tokenKey: __replace__
  certificate: __replace__
  privateKey: __replace__

pgbouncer:
  image: gcr.io/oursky-kube/pgbouncer:git-d292e5e7c1
  poolSizeSession: "9"
  poolSizeTransaction: "1"
  resources:
    requests:
      cpu: "100m"
      memory: "64Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
